name: tests

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          pytest --cov=. --cov-report=xml --cov-report=term-missing --cov-report=html --cov-fail-under=80

      - name: Upload HTML coverage
        uses: actions/upload-artifact@v4
        with:
          name: html-coverage
          path: htmlcov

      - name: Pytest Coverage Comment
        uses: MishaKav/pytest-coverage-comment@v1
        with:
          pytest-coverage-path: ./coverage.xml
          title: "Test coverage"
